use_frameworks!

platform :ios, '10.0'

target 'ChatDeNew_Example' do
  
  pod 'SwiftyJSON'
  pod 'Cosmos'
  pod 'ChatDeNew', :path => '../'

  target 'ChatDeNew_Tests' do
    inherit! :search_paths

    
  end
end

